FROM debian:latest

RUN apt update -y
RUN apt install -y libportmidi0 libportmidi-dev curl gcc

ENV PATH="$HOME/.cargo/bin:${PATH}"
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

COPY . /app

RUN cd /app && ~/.cargo/bin/cargo fmt --check
RUN cd /app && ~/.cargo/bin/cargo clippy
RUN cd /app && ~/.cargo/bin/cargo install --verbose --path .
