FROM archlinux:latest

RUN pacman --noconfirm -Syu \
    && pacman --noconfirm -S portmidi rustup gcc \
    && rustup default stable

COPY . /app

RUN cd /app && cargo fmt --check
RUN cd /app && cargo clippy
RUN cd /app && cargo install --verbose --path .
