name: Release

on:
  workflow_run:
    workflows: [Rust]
    types: [completed]
    branches: [ "master" ]

# TODO: get version for tag (fail if tags exists)
jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: rust.yml
      - run: |
          ls -l *
          cp lmi-ubuntu/target/release/lilypond-midi-input .
      - name: Get version
        id: version
        run: |
          sudo apt install -y libportmidi0
          chmod +x lilypond-midi-input
          echo "VERSION='v$(lilypond-midi-input --version | grep -oP '[0-9]+\.[0-9]+\.[0-9]+$')'" >> $GITHUB_OUTPUT
      - name: Create CHANGELOG.latest file
        run: cp "$(ls -v lmi-ubuntu/changelog/* | tail -1)" CHANGELOG.latest
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.VERSION }}
          body_path: CHANGELOG.latest
          files: lilypond-midi-input

